### ISSUE TITLE
Homes reset on restart

### ISSUE THREAD

**Issue by Cpt-Dingus** [MabelMedia-LLC/Fabric-Mods#3]
Every time minecraft restarts, /home results in a `[12:24:11] [Render thread/INFO]: [System] [CHAT] An unexpected error occurred trying to execute that command`. Running `/sethome` again makes it work.

Tested on 1.20.6 and 1.20.4, Fabric 0.15.11

**Comment by MabelYT** [comment]
What Version Of The Mod Are You Using?

**Comment by Cpt-Dingus** [comment]
1.1.6

**Comment by MabelYT** [comment]
The Latest Version Is Only Currently Available For Version 1.21.

**Comment by MabelYT** [comment]
Ok, A 1.20.4 Backport Of v1.2.4 Is Now Available. Please Open A New Issue If The New Version Has THe Same Issue.

**Comment by Cpt-Dingus** [comment]
Looks good, thanks!

**Comment by Cpt-Dingus** [comment]
Actually, it doesn't seem to launch now:

```
Exception caught from launcher
java.lang.RuntimeException: Error creating Mixin config super_simple_home.mixins.json for mod super_simple_home
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config super_simple_home.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 6 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.6 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1627)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 9 more
Exiting with ERROR```

**Comment by Cpt-Dingus** [comment]
Full log: https://mclo.gs/C4epgnV
